version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      depends_on:
        - db
      ports:
        - "5000:5000"
      volumes:
        - .:/emptyLeg
      env_file:
        - .env
      
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
